### PR TITLE
fix for issues #99, #107

### PR DESCRIPTION
**Pull request by topic2k**

### CODE REVIEW

**Comment by timeyyy** [comment]
Did you run the tests? unfortunately not all tests are running from travis.

**Comment by topic2k** [comment]
No, i didn't. Are those tests other than travis tests?

**Comment by timeyyy** [comment]
it is the same test suite, but different tests run depending on what operating system and freezers are installed, you can find the tests in the esky folder, (travis only checks for linux not windows)

**Comment by topic2k** [comment]
Ok, i run the test with py2:
```
py -2 -m pytest esky/tests/ -x
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
rootdir: c:\Python27\Lib\site-packages\esky\tests, inifile:
collected 38 items

esky\tests\test_esky.py ......................................

========================= 38 passed in 24.46 seconds ==========================
```
and with py3:
```
py -3.4 -m pytest esky/tests/ -x
============================= test session starts =============================
platform win32 -- Python 3.4.3, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
rootdir: c:\Python34\Lib\site-packages\esky\tests, inifile:
collected 0 items / 1 errors

=================================== ERRORS ====================================
________________________ ERROR collecting test_esky.py ________________________
_pytest\python.py:606: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
py\_path\local.py:650: in pyimport
    __import__(modname)
E     File "c:\Python34\Lib\site-packages\esky\__init__.py", line 254
E       except OSError, e:
E                     ^
E   SyntaxError: invalid syntax
=========================== 1 error in 0.13 seconds ===========================
```

**Comment by topic2k** [comment]
ok, will do some test now.

**Comment by topic2k** [comment]
what i did now, is:
* deleted site-packages/esky
* pip3.4 install esky
* py -3.4 -m pytest esky/tests/ -x : failed
* applied #111 changed import for py2exe.distutils_buildexe
* py -3.4 -m pytest esky/tests/ -x : failed
  * the test starts and then i get a crash of script1.exe
  * after closing the crash message info window some more output comes: (last lines)
```
---------------------------- Captured stderr call -----------------------------
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
===================== 1 failed, 2 passed in 38.70 seconds =====================
```
* made the changes from this commit/PR
* py -3.4 -m pytest esky/tests/ -x : same failure as above

So i think this commit/PR doesn't work and i can close/delete it?

**Comment by timeyyy** [comment]
no no no, don't delete this, please read my above message about the test suite, to summarize
`python2 -m pytest`
`pip3 install esky`

manually test esky with python3, you can use the tutorial/stage1 if you like. just edit the setup.py to use py2exe instead of cxfreeze then run
`python3 setup.py bdist_esky`

unzip and make sure it runs

**Comment by topic2k** [comment]
With python2 i've already tested successfull (some comments above).
On python3 the script is freezed/zipped, but when i run it, it chrashes and gives me this error
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
```
Is this the same problem as in #104?

**Comment by timeyyy** [comment]
It does seemm like it...

**Comment by rfk** [comment]
So, is this the same as #104, but showing up in windows instead of OSX?

**Comment by JPFrancoia** [comment]
What freezer was used ?

**Comment by rfk** [comment]
Over in #104, we figured out a minimal set of modules that must be available to python during its startup sequence.  I think this is a new requirement for python3, related to bootstrapping the `io` module and `sys.stdin` and similar.  The list is:

```
_weakrefset.pyc abc.pyc     codecs.pyc  encodings   io.pyc
```

So, we need to find a way to make these available to the py2exe bootstrap exe.  This probably means creating a `library.zip` or similar in the top-level bootstrap env, or perhaps appending them to the bootstrap executable itself.  Unfortunately I don't have access to a windows box at the moment, but if anyone's feeling adventurous, I can give you some pointers on how move ahead with this.

**Comment by rfk** [comment]
In fact, there's a comment in f_py2exe that says `"There's no need to copy library.zip into the bootstrap env..."`.  One way to see if this will help fix the problem, would be to copy the library.zip from the version subfolder into the bootstrap env, and see if that lets things run.

**Comment by timeyyy** [comment]
@rfk, I will try it out when I get home

**Comment by topic2k** [comment]
Is the bootstrap env the folder where the bootstrap exe is in? I've copied library.zip into it, but it's still crashing with the codec/encoding error.

**Comment by timeyyy** [comment]
This code is correct any way, py2exe doesn't compile in this commit  14d7d0ab341bc9385d154d539b51906ae5c7530d, after applying this patch it works.

**Pull request merged**
