### PR TITLE
Little fix to solve #70.

### PR DESCRIPTION
**Pull request by JPFrancoia**

### CODE REVIEW

**Comment by timeyyy** [comment]
Is it passing tests after applying this patch?

**Comment by JPFrancoia** [comment]
Which tests ? Travis ?

**Comment by timeyyy** [comment]
the travis tests are run on a linux server so they cannot test the code for mac specific stuff. Have a look at the testing section of our contribution page https://github.com/cloudmatrix/esky/wiki/Contributing

**Comment by timeyyy** [comment]
@JPFrancoia did you try running the tests against the patch?

**Comment by JPFrancoia** [comment]
I will, I'm waiting to borrow a Mac and will do it asap.

**Comment by JPFrancoia** [comment]
```
python -m pytest esky/tests/
============================================================================= test session starts ==============================================================================
platform darwin -- Python 2.7.10, pytest-2.8.3, py-1.4.30, pluggy-0.3.1
rootdir: /Users/chembrows/Desktop/esky, inifile: 
collected 38 items 

esky/tests/test_esky.py ......................................

========================================================================== 38 passed in 13.95 seconds ==========================================================================
```

Yep, it works.

**Comment by timeyyy** [comment]
and it works on py3 as well?

**Comment by JPFrancoia** [comment]
I don't think so:
```
python3 -m pytest esky/tests/
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.4.3, pytest-2.8.3, py-1.4.30, pluggy-0.3.1
rootdir: /Users/chembrows/Desktop/esky, inifile: 
collected 0 items / 1 errors 

==================================================================================== ERRORS ====================================================================================
___________________________________________________________________ ERROR collecting esky/tests/test_esky.py ___________________________________________________________________
/usr/local/lib/python3.4/site-packages/_pytest/python.py:606: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python3.4/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
E     File "/Users/chembrows/Desktop/esky/esky/__init__.py", line 632
E       except Exception, e:
E                       ^
E   SyntaxError: invalid syntax
=========================================================================== 1 error in 0.11 seconds ============================================================================
```

This syntax to catch the exceptions are from python 2 right ?

**Comment by timeyyy** [comment]
Ö, forgot my py3 conversion isnt finished yet. Manual testing is always a royal pain so i might merge this and we will see if we get complaints.. 

Would you actually be willing to help me test the py3k code on mac as i do not have one?

**Comment by JPFrancoia** [comment]
Yep, no matter, I regularly have access to a mac.

**Pull request merged**
