### PR TITLE
Fix #113. Can now apply local and remote patches.

### LINKED ISSUE #113: Patch doesn't apply py3.5 linux
Hi,

I have a little problem with the patches. When I try to apply a patch, I get this error:

```
Traceback (most recent call last):
  File "/home/djipey/informatique/python/ChemBrows/updater.py", line 59, in run
    self.app.auto_update()
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 626, in auto_update
    self._do_auto_update(version, callback)
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 674, in _do_auto_update
    self.fetch_version(version, callback)
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 716, in fetch_version
    loc = self.version_finder.fetch_version(self, version, callback)
  File "/usr/lib/python3.5/site-packages/esky/finder.py", line 80, in fetch_version
    for status in self.fetch_version_iter(app,version):
  File "/usr/lib/python3.5/site-packages/esky/finder.py", line 230, in fetch_version_iter
    self._prepare_version(app,version,local_path)
  File "/usr/lib/python3.5/site-packages/esky/finder.py", line 332, in _prepare_version
    apply_patch(uppath,f)
  File "/usr/lib/python3.5/site-packages/esky/patch.py", line 294, in apply_patch
    Patcher(target,stream,**kwds).patch()
  File "/usr/lib/python3.5/site-packages/esky/patch.py", line 569, in patch
    getattr(self,"_do_" + _COMMANDS[cmd])()
IndexError: list index out of range
```

I started myprogram_1.0, and the patch myprogram_1.1_from1.0.patch is present at http://localhost:8000

Also, applying updates from the full zip completely works, either with a local and a remote server.

EDIT:

This is from Linux, using cx_Freeze

### PR DESCRIPTION
**Pull request by JPFrancoia**
A EOFError exception is raised when trying to apply a local patch, but an IndexError is raised when the patch is downloaded from a remote server.

Solves the issue for both remote and local server.

### CODE REVIEW

**Comment by timeyyy** [comment]
How can I go about testing this?

**Comment by JPFrancoia** [comment]
Use the following zip (simply the stage 3 of the tuto):

[esky_test_patch.zip](https://github.com/cloudmatrix/esky/files/76271/esky_test_patch.zip)


First, build the esky app with:

```python setup.py bdist_esky_patch```

Then change the version number in setup.py, to a higher one.

To test the local patch, use this command in the dist folder created by esky:

```python -m http.server 8000```

To test the remote patch, upload the patch in the dist folder onto a remote server. I used an http server provided by OVH (it's an apache one, shared. That's where I'm going to run my apps, once in production).
You will have to modify the example.py script to use the correct URL.

**Comment by timeyyy** [comment]
where is the eoferror getting raised? is the fact that an eoferror is not being raised also an issue? i.e i don't want to simply be masking a deeper issue here

**Comment by JPFrancoia** [comment]
Yes sorry, my bad, I was not precise engouh.

The fact that an oeferror is not being raised is the issue in this situation. For local patches, eoferror is raised, which is the handled case, and leads to the proper behaviour.

When the patch is remote however, an InderError is raised instead of the eoferror, and leads to an unhandled case, and makes the update crash.

Sorry if I wasn't clear enough.

**Comment by timeyyy** [comment]
So by simply catching the IndexError, isn't this just hiding a deeper bug?

**Comment by JPFrancoia** [comment]
I have absolutely no idea.

```python
while True:
   cmd = self._read_command()
   getattr(self,"_do_" + _COMMANDS[cmd])()
```

Just 2 lines above, there is a while loop trying to read. So at one moment, it might try to read an unexisting index. Why it happens for a remote patch and not a local one, I have no idea.

**Comment by timeyyy** [comment]
Is this a complete fix for the issue?

**Comment by JPFrancoia** [comment]
It does fix the original issue #128 , which was reported for Linux (but was also present on Windows).

Patches still don't work for OSX, but for another reason, I'm working on it -> It follows the issue #129 .

**Comment by timeyyy** [comment]
@JPFrancoia Sorry man, i messed around with the git history. Would you be able to run git pull --rebase? If it's still wonky you might have to do a cherry-pick and repush the patch. I'm going to merge this and just make a note of it to test a bit more later.

**Comment by JPFrancoia** [comment]
What do you mean ? What should I rebase ?

**Comment by timeyyy** [comment]
bash
```
git checkout master
git pull --rebase upstream  (where upstream is cloudmatrix repo)

git checkout 
```

**Comment by JPFrancoia** [comment]
Clearly, too complicated. I don't have time to do that. Can't I simply close this PR and make a new one ?

**Comment by timeyyy** [comment]
yes

**Pull request closed without merging**
