### PR TITLE
Fix for two bytes issues

### PR DESCRIPTION
**Pull request by JPFrancoia**

### CODE REVIEW

**Comment by JPFrancoia** [comment]
Why is travis failing ?

The command "sudo apt-get install cx-freeze" failed and exited with 100 during .

Because of cx-freeze, or because of my code ?

**Comment by timeyyy** [comment]
nah, they are updating there servers.

**Comment by JPFrancoia** [comment]
Ok. Will the tests be re-ran automatically ?

**Comment by timeyyy** [comment]
i don't think so, but they are the same test you run locally so you can test and post the results

**Comment by JPFrancoia** [comment]
So here are the results of the tests:
[out.txt](https://github.com/cloudmatrix/esky/files/53584/out.txt)

Out of 40, 39 passed. The only remaining is test_esky_cxfreeze_needsroot, but as discussed in #113, it only doesn't work for me.

If I run it with sudo:

[out2.txt](https://github.com/cloudmatrix/esky/files/53585/out2.txt)

It passes.

**Comment by timeyyy** [comment]
Are you trying to solve multiple issues with this commit? For clarity can i suggest working each seperate issue in a different branches and making a pull for each one seperatley, Even if it is not complete then we can discuss and work from there and merge the issue when its completley fixed into master. 

So a puill request dealing with the issue 113 and another for 114

**Comment by timeyyy** [comment]
@JPFrancoia this patch isn't finish is that correct? Do you know how i can move the correction from djipey to a new pull request as they target another issue...

**Pull request closed without merging**
